language: cpp
sudo: required
dist: trusty

env:
#    - IMAGE=debian_9 BUILDTYPE=Debug
    - IMAGE=debian_9 BUILDTYPE=Release
#    - IMAGE=docker-debian-8 BUILDTYPE=Debug
#    - IMAGE=docker-debian-8 BUILDTYPE=Release
#    - IMAGE=docker-ubuntu-17.10 BUILDTYPE=Debug
#    - IMAGE=docker-ubuntu-17.10 BUILDTYPE=Release

services:
    - docker
    
before_script:
    - docker run --name build -i -d -v"$PWD:/src" eugenwintersberger/$IMAGE:latest
    - docker exec -it build ls
    - docker exec -it build bash -c "git submodule init"
    - docker exec -it build bash -c "git submodule update --remote"
    - docker exec -it build bash -c "mkdir build"
    
    
script:
    - docker exec -e BUILDTYPE -it build bash -c "cd build && cmake -DWITH_CONAN=ON -DCMAKE_BUILD_TYPE=$BUILDTYPE .."
    - docker exec -e CONAN_LOGIN_USERNAME -e CONAN_PASSWORD -it build bash -c "conan upload --all -c -rdesypackages Boost/*"
    - docker exec -e CONAN_LOGIN_USERNAME -e CONAN_PASSWORD -it build bash -c "conan upload --all -c -rdesypackages hdf5/*"
    - docker exec -e CONAN_LOGIN_USERNAME -e CONAN_PASSWORD -it build bash -c "conan upload --all -c -rdesypackages h5cpp/*"
    - docker exec -e CONAN_LOGIN_USERNAME -e CONAN_PASSWORD -it build bash -c "conan upload --all -c -rdesypackages zlib/*"
    - docker exec -e CONAN_LOGIN_USERNAME -e CONAN_PASSWORD -it build bash -c "conan upload --all -c -rdesypackages bzip2/*"
    - docker exec -e CONAN_LOGIN_USERNAME -e CONAN_PASSWORD -it build bash -c "conan upload --all -c -rdesypackages gtest/*"
    - docker exec -e CONAN_LOGIN_USERNAME -e CONAN_PASSWORD -it build bash -c "conan upload --all -c -rdesypackages pnicore/*"
    - docker exec -e CONAN_LOGIN_USERNAME -e CONAN_PASSWORD -it build bash -c "conan upload --all -c -rdesypackages pniio/*"
    - docker exec -e BUILDTYPE -it build bash -c "cd build && cmake --build . --target all --config $BUILDTYPE"
    - docker exec -e BUILDTYPE -it build bash -c "cd build && cmake --build . --target check --config $BUILDTYPE"
    
after_script:
    - docker container stop build
    
